In [2]:
import sqlite3
import pandas as pd

con=sqlite3.connect('C:\\Users\\muhju\\Downloads\\sem 3 ojt\\proj 3.1\\data\\raw\\ipl.db')
def q(sql):
    return pd.read_sql(sql, con)

In [3]:
def run_sql_file(path):
    with open(path, 'r') as f:
        script = f.read()
    con.executescript(script)
    con.commit()
    print('ran', path)

In [4]:
run_sql_file('C:\\Users\\muhju\\Downloads\\sem 3 ojt\\proj 3.1\\sql\\test.sql')

ran C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\test.sql

In [5]:
run_sql_file('C:\\Users\\muhju\\Downloads\\sem 3 ojt\\proj 3.1\\sql\\01_nulls_and_blanks.sql')

ran C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\01_nulls_and_blanks.sql

In [6]:
q(""" SELECT COUNT(*) AS blank_before
FROM deliveries
WHERE TRIM(bowler_type)='';""")

   blank_before
0             8

In [7]:
q(""" SELECT COUNT(*) AS null_after
FROM v_PLAYERS_clean
WHERE field_pos_clean IS NULL;""")

   null_after
0         700

In [8]:
run_sql_file('C:\\Users\\muhju\\Downloads\\sem 3 ojt\\proj 3.1\\sql\\02_merge_categories.sql')

ran C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\02_merge_categories.sql

In [15]:
q(""" SELECT DISTINCT team_name
FROM teams
ORDER BY team_name;""")

                      team_name
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13      Rising Pune Supergiants
14  Royal Challengers Bangalore
15          Sunrisers Hyderabad

In [16]:
q(""" SELECT DISTINCT team_name_clean
FROM v_TEAMS_clean
ORDER BY team_name_clean
;""")

                team_name_clean
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13  Royal Challengers Bangalore
14          Sunrisers Hyderabad

In [9]:
run_sql_file('C:\\Users\\muhju\\Downloads\\sem 3 ojt\\proj 3.1\\sql\\03_venue_names.sql')

ran C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\03_venue_names.sql

In [ ]:
q(""" SELECT venue, COUNT(*) AS matches
FROM matches
WHERE venue IN('Wankhede Stadium', 'Wankhede Stadium, Mumbai')
GROUP BY venue;""")

                      venue  matches
0          Wankhede Stadium       73
1  Wankhede Stadium, Mumbai       57

In [19]:
q(""" SELECT venue,COUNT(*) AS matches
FROM matches
GROUP BY venue
ORDER BY matches DESC
LIMIT 10;""")

                                       venue  matches
0                               Eden Gardens       77
1                           Wankhede Stadium       73
2                      M Chinnaswamy Stadium       65
3                           Feroz Shah Kotla       60
4                   Wankhede Stadium, Mumbai       57
5  Rajiv Gandhi International Stadium, Uppal       49
6            MA Chidambaram Stadium, Chepauk       48
7                     Sawai Mansingh Stadium       47
8        Dubai International Cricket Stadium       46
9   MA Chidambaram Stadium, Chepauk, Chennai       38

In [20]:
q(""" SELECT venue_clean, COUNT(*) AS matches
FROM v_matches_venue
WHERE venue_clean IN('Wankhede Stadium', 'Wankhede Stadium, Mumbai')
GROUP BY venue_clean;""")

        venue_clean  matches
0  Wankhede Stadium      130

In [21]:
q(""" SELECT venue_clean,COUNT(*) AS matches
FROM v_matches_venue
GROUP BY venue_clean
ORDER BY matches DESC
LIMIT 10;""")

                           venue_clean  matches
0                     Wankhede Stadium      130
1                         Eden Gardens      104
2               MA Chidambaram Stadium       95
3                M Chinnaswamy Stadium       89
4   Rajiv Gandhi International Stadium       87
5               Sawai Mansingh Stadium       66
6                     Feroz Shah Kotla       60
7  Dubai International Cricket Stadium       46
8                 Arun Jaitley Stadium       41
9                Narendra Modi Stadium       37

In [26]:
run_sql_file('C:\\Users\\muhju\\Downloads\\sem 3 ojt\\proj 3.1\\sql\\04_dedupe_venues.sql')

ran C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\04_dedupe_venues.sql

In [22]:
q(""" SELECT COUNT(*) AS rows, COUNT(DISTINCT venue) AS distinct_venues
FROM venues;""")

   rows  distinct_venues
0    63               59

In [23]:
q(""" SELECT COUNT(*),venue,city
FROM venues
GROUP BY venue
ORDER BY COUNT(*) DESC
LIMIT 10;""")

   COUNT(*)                                              venue       city
0         2                            Sharjah Cricket Stadium        NaN
1         2  Maharaja Yadavindra Singh International Cricke...     Mohali
2         2                Dubai International Cricket Stadium        NaN
3         2                 Dr DY Patil Sports Academy, Mumbai     Mumbai
4         1                   Zayed Cricket Stadium, Abu Dhabi  Abu Dhabi
5         1                           Wankhede Stadium, Mumbai     Mumbai
6         1                                   Wankhede Stadium     Mumbai
7         1       Vidarbha Cricket Association Stadium, Jamtha     Nagpur
8         1                                    SuperSport Park  Centurion
9         1                         Subrata Roy Sahara Stadium       Pune

In [27]:
q(""" SELECT COUNT(*) AS rows,COUNT(DISTINCT venue) AS distinct_venues
FROM v_venues_clean;""")

   rows  distinct_venues
0    59               59

In [28]:
q(""" SELECT COUNT(*),venue,city
FROM v_venues_clean
GROUP BY venue
ORDER BY COUNT(*) DESC
LIMIT 10;""")

   COUNT(*)                                             venue            city
0         1                  Zayed Cricket Stadium, Abu Dhabi       Abu Dhabi
1         1                          Wankhede Stadium, Mumbai          Mumbai
2         1                                  Wankhede Stadium          Mumbai
3         1      Vidarbha Cricket Association Stadium, Jamtha          Nagpur
4         1                                   SuperSport Park       Centurion
5         1                        Subrata Roy Sahara Stadium            Pune
6         1                                  St George's Park  Port Elizabeth
7         1                              Sheikh Zayed Stadium       Abu Dhabi
8         1                           Sharjah Cricket Stadium         Sharjah
9         1  Shaheed Veer Narayan Singh International Stadium          Raipur

In [29]:
run_sql_file('C:\\Users\\muhju\\Downloads\\sem 3 ojt\\proj 3.1\\sql\\05_city_fallback.sql')

ran C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\05_city_fallback.sql

In [38]:
q(""" SELECT  venue,
        COUNT(*) AS no_city
FROM matches
WHERE city IS NULL
GROUP BY venue;""")

                                 venue  no_city
0  Dubai International Cricket Stadium       33
1              Sharjah Cricket Stadium       18

In [30]:
q(""" SELECT city_clean FROM v_city_clean
WHERE city_clean IN('UNKNOWN');""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [ ]:
q(""" SELECT city_clean FROM v_city_clean
LIMIT 5;""")

  city_clean
0  Bangalore
1  Hyderabad
2       Pune
3     Rajkot
4     Indore

In [37]:
run_sql_file('C:\\Users\\muhju\\Downloads\\sem 3 ojt\\proj 3.1\\sql\\06_season_year.sql')

ran C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\06_season_year.sql

In [39]:
q(""" SELECT season,
        COUNT(*) AS matches
FROM matches
WHERE season='2020/21'
GROUP BY season;""")

    season  matches
0  2020/21       60