In [2]:
import sqlite3
import pandas as pd

con=sqlite3.connect('C:\\Users\\muhju\\Downloads\\sem 3 ojt\\proj 3.1\\data\\raw\\ipl.db')
def q(sql):
    return pd.read_sql(sql, con)

In [3]:
def run_sql_file(path):
    with open(path, 'r') as f:
        script = f.read()
    con.executescript(script)
    con.commit()
    print('ran', path)

In [4]:
q("""
  --what is the strike rate of every batter in death overs?
  
  SELECT batter,
  ROUND(100.0*SUM(batter_runs))/SUM(
    CASE
      WHEN is_wide_ball=0 AND is_no_ball=0
      THEN 1
      ELSE 0
    END) AS strike_rate

 FROM deliveries
 WHERE over_number>=15 AND is_super_over=0
 GROUP BY batter
 ORDER BY strike_rate DESC;""")

             batter  strike_rate
0          WG Jacks   483.333333
1          DT Patil   400.000000
2        KT Maphaka   400.000000
3            L Wood   300.000000
4          PA Reddy   300.000000
..              ...          ...
637     Sunny Gupta     0.000000
638          U Kaul     0.000000
639  V Pratap Singh     0.000000
640   Y Prithvi Raj     0.000000
641      YA Abdulla     0.000000

[642 rows x 2 columns]

In [5]:
run_sql_file(r'C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\09_analysis_views.sql')

ran C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\09_analysis_views.sql

In [6]:
q(""" SELECT * FROM v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [7]:
q(""" SELECT phase , COUNT(*) FROM v_ball GROUP BY phase;""")

       phase  COUNT(*)
0      Death     65488
1     Middle    132173
2  Powerplay     90390

In [8]:
q(""" SELECT * FROM v_innings;""")

,match_id,innings,batting_team,bowling_team,runs,wickets,legal_balls
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,222,3,120
1,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,82,10,91
2,335983,1,Chennai Super Kings,Punjab Kings,240,5,120
3,335983,2,Punjab Kings,Chennai Super Kings,207,4,120
4,335984,1,Rajasthan Royals,Delhi Capitals,129,8,120
...,...,...,...,...,...,...,...
2413,1529284,2,Sunrisers Hyderabad,Mumbai Indians,249,4,112
2414,1529285,1,Royal Challengers Bangalore,Gujarat Titans,155,10,116
2415,1529285,2,Gujarat Titans,Royal Challengers Bangalore,158,6,95
2416,1529286,1,Rajasthan Royals,Delhi Capitals,225,6,120
2417,1529286,2,Delhi Capitals,Rajasthan Royals,226,3,115

In [9]:
q(""" SELECT * FROM v_match_totals;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_winner,toss_decision,team1,team2,first_innings_runs,bat_first_team,chase_won
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field,Royal Challengers Bangalore,Kolkata Knight Riders,222,Kolkata Knight Riders,0
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field,Sunrisers Hyderabad,Royal Challengers Bangalore,207,Sunrisers Hyderabad,0
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field,Rising Pune Supergiant,Mumbai Indians,184,Mumbai Indians,1
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field,Gujarat Lions,Kolkata Knight Riders,183,Gujarat Lions,1
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,Punjab Kings,field,Punjab Kings,Rising Pune Supergiant,163,Rising Pune Supergiant,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1182,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field,Delhi Capitals,Royal Challengers Bangalore,75,Delhi Capitals,1
1183,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,Rajasthan Royals,field,Punjab Kings,Rajasthan Royals,222,Punjab Kings,1
1184,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat,Mumbai Indians,Sunrisers Hyderabad,243,Mumbai Indians,1
1185,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,Gujarat Titans,field,Royal Challengers Bangalore,Gujarat Titans,155,Royal Challengers Bangalore,1
1186,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat,Rajasthan Royals,Delhi Capitals,225,Rajasthan Royals,1

In [10]:
q(""" SELECT COUNT(*) FROM v_innings ;""")

   COUNT(*)
0      2418

In [11]:
q(""" SELECT COUNT(*) FROM v_match_totals ;""")

   COUNT(*)
0      1187

In [12]:
q("""
  -- give the list of players with highest runs scored in IPL history
  -- top 5
  SELECT
      batter AS player,
      SUM(batter_runs) AS total_runs
  FROM v_ball
  GROUP BY batter
  ORDER BY total_runs DESC
  LIMIT 5;""")

      player  total_runs
0    V Kohli        9040
1  RG Sharma        7183
2   S Dhawan        6769
3  DA Warner        6565
4   KL Rahul        5655

In [13]:
q("""
  -- give the list of players with highest sixes scored in IPL history
  -- top 10
  SELECT
      batter AS player,
      SUM(CASE WHEN batter_runs = 6 THEN 1 ELSE 0 END) AS total_sixes
  FROM v_ball
  GROUP BY batter
  ORDER BY total_sixes DESC
  LIMIT 10;""")

           player  total_sixes
0        CH Gayle          357
1       RG Sharma          311
2         V Kohli          307
3        MS Dhoni          264
4  AB de Villiers          251
5       DA Warner          236
6       SV Samson          234
7        KL Rahul          232
8      AD Russell          223
9      KA Pollard          223

In [14]:
q("""
  SELECT
       batter AS player,
       SUM(CASE WHEN is_legal = 1 THEN 1 ELSE 0 END)AS total_balls_faced,
       ROUND(100.0*SUM(batter_runs))/SUM(
           CASE
             WHEN is_wide_ball=0 AND is_no_ball=0
             THEN 1
             ELSE 0
           END) AS strike_rate,
       SUM(batter_runs) AS total_runs
  FROM v_ball
  GROUP BY batter
  ORDER BY total_balls_faced DESC ;""")

             player  total_balls_faced  strike_rate  total_runs
0           V Kohli               6730   134.323923        9040
1         RG Sharma               5396   133.117124        7183
2          S Dhawan               5302   127.668804        6769
3         DA Warner               4675   140.427807        6565
4         AM Rahane               4141   125.428640        5194
..              ...                ...          ...         ...
722     Sunny Gupta                  1     0.000000           0
723          U Kaul                  1     0.000000           0
724  V Pratap Singh                  1     0.000000           0
725   Y Prithvi Raj                  1     0.000000           0
726      YA Abdulla                  1     0.000000           0

[727 rows x 4 columns]

In [15]:
q("""
-- Find an ideal middle-order batter who can lift the run rate in overs 7 to 15. 

SELECT
    batter,
    SUM(batter_runs) AS runs,
    SUM(is_legal) AS balls,
    ROUND(
        100.0 * SUM(batter_runs) / NULLIF(SUM(is_legal), 0),
        2
    ) AS strike_rate
FROM v_ball
WHERE over_number BETWEEN 7 AND 15
GROUP BY batter
HAVING SUM(is_legal) >= 50
ORDER BY strike_rate DESC, runs DESC;
""")

            batter  runs  balls  strike_rate
0    V Suryavanshi   162     68       238.24
1    Priyansh Arya   189     87       217.24
2       C Connolly   159     79       201.27
3        SP Narine   488    260       187.69
4          PD Salt   322    173       186.13
..             ...   ...    ...          ...
265       JDP Oram    56     72        77.78
266        WA Mota    43     61        70.49
267       A Mishra   134    196        68.37
268        B Kumar    55     85        64.71
269  Kuldeep Yadav    42     70        60.00

[270 rows x 4 columns]

In [16]:
q("""
  --Find a finisher : highest strike rate in the last five overs.
  
  SELECT batter,SUM(batter_runs) AS runs,SUM(is_legal) AS balls,
                ROUND (100.0*SUM(batter_runs)/SUM(is_legal),2) AS strike_rate
                
    FROM v_ball
    WHERE phase="Death"
    GROUP BY batter
    HAVING balls>500
    ORDER BY strike_rate DESC
    LIMIT 10;""")

           batter  runs  balls  strike_rate
0  AB de Villiers  1868    829       225.33
1         RR Pant  1035    513       201.75
2      AD Russell  1432    724       197.79
3         V Kohli  1525    807       188.97
4      MP Stoinis   962    521       184.64
5       RG Sharma  1527    837       182.44
6        KL Rahul   907    502       180.68
7        MS Dhoni  3468   1965       176.49
8        DJ Bravo   909    516       176.16
9      KD Karthik  1904   1091       174.52

In [17]:
q(""" SELECT * FROM v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [18]:
q("""
  --Find a powerplay opener who attacks from ball one.
  
  SELECT batter,SUM(batter_runs) AS runs,SUM(is_legal) AS balls,
                ROUND (100.0*SUM(batter_runs)/SUM(is_legal),2) AS strike_rate
                
    FROM v_ball
    WHERE phase="Powerplay"
    GROUP BY batter
    HAVING balls>500
    ORDER BY strike_rate DESC
    LIMIT 10;""")

            batter  runs  balls  strike_rate
0  Abhishek Sharma  1287    744       172.98
1        SP Narine  1174    688       170.64
2      YBK Jaiswal  1579    984       160.47
3   P Simran Singh  1070    687       155.75
4      JM Bairstow   944    623       151.52
5          PP Shaw  1347    917       146.89
6         V Sehwag  1593   1096       145.35
7          CA Lynn   779    537       145.07
8       JC Buttler  1789   1257       142.32
9      RA Tripathi  1013    721       140.50

In [19]:
# who is the most reliable in a chase - strike rate batting second?

q("""
  SELECT batter,SUM(batter_runs) AS runs,SUM(is_legal) AS balls,
                  ROUND (100.0*SUM(batter_runs)/SUM(is_legal),2) AS strike_rate
                  
      FROM v_ball
      WHERE innings=2
      GROUP BY batter
      HAVING balls>500
      ORDER BY strike_rate DESC
      LIMIT 10;""")

            batter  runs  balls  strike_rate
0        SP Narine   869    507       171.40
1       AD Russell  1130    660       171.21
2  Abhishek Sharma  1108    648       170.99
3         N Pooran  1218    729       167.08
4         V Sehwag  1427    869       164.21
5       GJ Maxwell  1164    734       158.58
6   P Simran Singh   832    527       157.87
7       JC Buttler  2289   1461       156.67
8      YBK Jaiswal  1351    875       154.40
9         SA Yadav  2131   1382       154.20

In [20]:
# which batter are hardest to bowl a dot ball to in the death overs?

q("""
   SELECT batter,COUNT(*) AS total_balls,
   SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END) AS dot_balls,
   ROUND(
        100.0*SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS dot_ball_percentage
FROM v_ball
WHERE phase = 'Death'
  AND is_legal = 1
GROUP BY batter
HAVING total_balls > 500
ORDER BY dot_ball_percentage ASC
LIMIT 10;
""")

           batter  total_balls  dot_balls  dot_ball_percentage
0       JP Duminy          516        104                20.16
1  AB de Villiers          829        175                21.11
2        SK Raina          521        111                21.31
3        KL Rahul          502        110                21.91
4         V Kohli          807        185                22.92
5        DJ Bravo          516        128                24.81
6       AT Rayudu          692        173                25.00
7       DA Miller          835        212                25.39
8        AR Patel          629        162                25.76
9       RA Jadeja         1240        323                26.05

# phase c

In [21]:
# how do runs and wickets differ across the three phases of an innings

q("""
  SELECT phase,
  SUM(is_legal) AS balls,
  SUM(total_runs) AS runs,
  ROUND(6.0*SUM(total_runs)/SUM(is_legal),2) AS  runs_per_over,
  SUM(is_wicket) AS wickets,
  ROUND(100.0*SUM(is_wicket)/SUM(is_legal),2) AS wicket_percentage
  FROM v_ball
  GROUP BY phase
  ORDER BY phase DESC;""")

       phase   balls    runs  runs_per_over  wickets  wicket_percentage
0  Powerplay   86921  116397           8.03     3483               4.01
1     Middle  128191  169160           7.92     5562               4.34
2      Death   62205  104056          10.04     5264               8.46

In [22]:
# which over of the innings is the most expensive

q("""
  SELECT over_number +1 AS over_number,
  ROUND(6.0*SUM(total_runs)/SUM(is_legal),2) AS  runs_per_over
  FROM v_ball
  GROUP BY over_number
  ORDER BY runs_per_over DESC;""")

    over_number  runs_per_over
0            20          11.39
1            19          10.53
2            18          10.12
3            17           9.46
4            16           9.05
5            15           8.74
6             6           8.68
7             5           8.65
8             4           8.63
9            14           8.43
10            3           8.37
11           13           8.17
12           12           8.13
13           11           7.96
14            9           7.77
15           10           7.66
16            2           7.60
17            8           7.47
18            7           6.98
19            1           6.28

In [23]:
# what is the average score at the end of the powerplay

q("""
  SELECT ROUND(AVG(pp_RUNS),2) AS avg_powerplay_score
  FROM (SELECT match_id,innings,SUM(total_runs) AS pp_runs
        FROM v_ball
        WHERE phase='Powerplay' AND innings IN(1,2)
        GROUP BY match_id,innings);""")

   avg_powerplay_score
0                48.14

In [24]:
q("""
  SELECT over_number +1 AS over_number,
  ROUND(6.0*SUM(is_wicket)/SUM(is_legal),2) AS  wickets_per_over
  FROM v_ball
  GROUP BY over_number
  ORDER BY wickets_per_over DESC;""")

    over_number  wickets_per_over
0            20              0.83
1            19              0.54
2            18              0.49
3            17              0.39
4            16              0.36
5            15              0.33
6            14              0.30
7            13              0.28
8            11              0.27
9             5              0.27
10           12              0.26
11            9              0.25
12            4              0.25
13            3              0.25
14            6              0.24
15           10              0.23
16            2              0.23
17            8              0.22
18            7              0.21
19            1              0.20

In [25]:
q("""
  SELECT over_number +1 AS over_number,
  ROUND(6.0*SUM(total_runs)/SUM(is_legal),2) AS  runs_per_over
  FROM v_ball
  WHERE over_number IN (0, 19)
  GROUP BY over_number
  ORDER BY over_number;""")

   over_number  runs_per_over
0            1           6.28
1           20          11.39

In [26]:
# the team wants the all-time wicket-takers

q("""
  SELECT bowler,
  SUM(is_wicket) AS wicket_taken
  FROM v_ball
  GROUP BY bowler
  ORDER BY wicket_taken DESC
  LIMIT 10;""")

       bowler  wicket_taken
0   YS Chahal           237
1     B Kumar           231
2   SP Narine           219
3    DJ Bravo           207
4    R Ashwin           205
5   JJ Bumrah           202
6   PP Chawla           201
7  SL Malinga           188
8   RA Jadeja           186
9    A Mishra           183

In [27]:
# who is the most economical bowler, counting only runs that were their fault.

q("""
  SELECT bowler,
  SUM(is_legal) AS balls,
  ROUND(6.0*SUM(bowler_runs)/SUM(is_legal),2) AS economy_rate
  FROM v_ball
  GROUP BY bowler
  HAVING balls>500
  ORDER BY economy_rate ASC
  LIMIT 10;""")

            bowler  balls  economy_rate
0         A Kumble    965          6.58
1   M Muralitharan   1524          6.68
2       DL Vettori    777          6.79
3        SP Narine   4507          6.79
4         DW Steyn   2176          6.92
5          J Botha    694          6.92
6         R Sharma    928          7.02
7  Harbhajan Singh   3416          7.08
8       SL Malinga   2827          7.14
9      Rashid Khan   3387          7.16

In [28]:
# which bowler takes a wicket most often - best strike rate in balls per wicket?

q("""
  SELECT
    bowler,
    SUM(is_legal) AS total_balls,
    SUM(bowler_wicket) AS total_wickets,
    ROUND(
        1.0 * SUM(is_legal) / SUM(bowler_wicket),
        2
    ) AS balls_per_wicket
FROM v_ball
GROUP BY bowler
HAVING total_wickets > 50
ORDER BY balls_per_wicket ASC
LIMIT 10;
""")

         bowler  total_balls  total_wickets  balls_per_wicket
0    AD Russell         1806            123             14.68
1  JR Hazlewood         1008             65             15.51
2      K Rabada         2112            133             15.88
3      MA Starc         1083             68             15.93
4   Imran Tahir         1316             82             16.05
5      HV Patel         2470            151             16.36
6    SL Malinga         2827            170             16.63
7      DJ Bravo         3120            183             17.05
8     YS Chahal         3941            228             17.29
9    Noor Ahmad          966             55             17.56

In [29]:
# which bowler gives away the fewest boundaries?
q("""
  SELECT
    bowler,
    SUM(is_legal) AS total_balls,
    SUM(CASE WHEN batter_runs IN(4,6) THEN 1 ELSE 0 END) boundaries,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs IN(4,6) THEN 1 ELSE 0 END)
        /SUM(is_legal),
        2) AS boundary_perc
    FROM v_ball
    WHERE is_legal = 1
    GROUP BY bowler
    HAVING total_balls>1000
    ORDER BY boundary_perc ASC
    LIMIT 10;""")

            bowler  total_balls  boundaries  boundary_perc
0   M Muralitharan         1524         170          11.15
1         R Bhatia         1636         188          11.49
2        SP Narine         4507         526          11.67
3         R Ashwin         4710         554          11.76
4         M Kartik         1149         138          12.01
5         SK Warne         1194         147          12.31
6         A Mishra         3371         420          12.46
7          PP Ojha         1899         242          12.74
8      Rashid Khan         3387         436          12.87
9  Harbhajan Singh         3416         441          12.91

In [30]:
q(""" SELECT * FROM v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [31]:
q("""SELECT CASE WHEN bowler_type LIKE 'Left%'               -- spin or pace 
       THEN 'Left arm' ELSE 'Right arm' END             -- branches of th 
       AS arm, 
       batsman_type, 
       ROUND(6.0*SUM(bowler_runs)/SUM(is_legal),2)      -- runs per over 
              AS economy, 
       ROUND(100.0*SUM(bowler_wicket)/SUM(is_legal),2)  -- bowler's wicke 
              AS wicket_pct 
FROM   v_ball                                           -- one row = one 
WHERE  TRIM(COALESCE(bowler_type,'')) <> ''             -- drop the blanks 
       AND batsman_type IS NOT NULL                     -- and this too 
GROUP  BY arm, batsman_type;""")

         arm    batsman_type  economy  wicket_pct
0   Left arm   Left hand Bat     8.81        5.13
1   Left arm  Right hand Bat     8.49        4.97
2  Right arm   Left hand Bat     8.33        4.46
3  Right arm  Right hand Bat     8.16        4.78

In [32]:
q("""
-- Which spinner is the best wicket-taker?

SELECT
    bowler,
    SUM(bowler_wicket) AS wicket,
    ROUND(
        100.0 * SUM(bowler_wicket) / SUM(is_legal),
        2
    ) AS wicket_perc
FROM v_ball
WHERE bowler_type LIKE '%Legbreak%'
   OR bowler_type LIKE '%Offbreak%'
   OR bowler_type LIKE '%Orthodox%'
   OR bowler_type LIKE '%Wrist spin%'
   OR bowler_type LIKE '%Googly%'
GROUP BY bowler
HAVING SUM(is_legal) > 500
ORDER BY wicket DESC
LIMIT 10;""")

            bowler  wicket  wicket_perc
0        YS Chahal     228         5.79
1        SP Narine     199         4.42
2        PP Chawla     192         4.99
3         R Ashwin     187         3.97
4        RA Jadeja     177         4.23
5         A Mishra     174         5.16
6      Rashid Khan     168         4.96
7  Harbhajan Singh     150         4.39
8         AR Patel     136         3.90
9    Kuldeep Yadav     109         4.90

In [33]:
q("""

SELECT
    bowler,
    SUM(is_legal) AS total_balls,
    SUM(bowler_runs) AS runs,
    ROUND(6.0*SUM(bowler_runs)/SUM(is_legal),2) AS economy
    FROM v_ball
    WHERE phase='Death'
    GROUP BY bowler
    HAVING total_balls>300
    ORDER BY economy ASC;""")

          bowler  total_balls  runs  economy
0      SP Narine         1075  1307     7.29
1     SL Malinga         1117  1464     7.86
2      JJ Bumrah         1393  1911     8.23
3       R Ashwin          601   825     8.24
4       DW Steyn          634   877     8.30
..           ...          ...   ...      ...
62    JD Unadkat          665  1214    10.95
63      AB Dinda          412   761    11.08
64     SM Curran          389   737    11.37
65  TU Deshpande          341   667    11.74
66     HH Pandya          320   640    12.00

[67 rows x 4 columns]

In [34]:
# we need a powerplay strike bowler . who takes most wicket in over 1 to 6
q("""

SELECT
    bowler,
    SUM(is_legal) AS total_balls,
    SUM(bowler_wicket) AS wicket,
    ROUND(
            100.0 * SUM(bowler_wicket) / SUM(is_legal),
            2
        ) AS wicket_perc
FROM v_ball
WHERE phase='Powerplay'
GROUP BY bowler
    HAVING total_balls>300
    ORDER BY wicket DESC;""")

            bowler  total_balls  wicket  wicket_perc
0          B Kumar         2453      89         3.63
1         TA Boult         1644      72         4.38
2        DL Chahar         1527      67         4.39
3   Sandeep Sharma         1728      64         3.70
4         UT Yadav         1446      58         4.01
..             ...          ...     ...          ...
75    DE Bollinger          324      11         3.40
76    Mukesh Kumar          354      11         3.11
77       SM Curran          570      11         1.93
78    M Theekshana          312      10         3.21
79       JO Holder          354       9         2.54

[80 rows x 4 columns]

In [35]:
# which bowler has the best dot-ball rate at the death?

q("""

SELECT
    bowler,
    SUM(is_legal) AS total_balls,
    SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END) AS dot_balls,
       ROUND(
            100.0*SUM(CASE WHEN total_runs = 0 THEN 1 ELSE 0 END) / SUM(is_legal),
            2
        ) AS dot_ball_percentage
FROM v_ball
WHERE phase='Death'
GROUP BY bowler
HAVING total_balls>300
ORDER BY dot_ball_percentage DESC;""")

            bowler  total_balls  dot_balls  dot_ball_percentage
0        SP Narine         1075        442                36.93
1         CV Varun          310        124                36.13
2       MG Johnson          302        132                35.76
3      Rashid Khan          594        228                35.02
4         DW Steyn          634        258                34.38
..             ...          ...        ...                  ...
62  Sandeep Sharma          783        245                24.39
63      TG Southee          348        113                23.85
64       IK Pathan          489        151                23.72
65         P Kumar          592        193                23.31
66        L Balaji          502        151                21.91

[67 rows x 4 columns]

In [36]:
run_sql_file(r'C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\08_matches_clean.sql')

ran C:\Users\muhju\Downloads\sem 3 ojt\proj 3.1\sql\08_matches_clean.sql

In [37]:
# does the toss winner win the match more often than not?

q("""
SELECT
    COUNT(*) AS decisive_matches,
    SUM(CASE WHEN toss_winner = match_winner THEN 1 ELSE 0 END) AS toss_winner_won,
    ROUND(
        100.0 * SUM(CASE WHEN toss_winner = match_winner THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS pct
FROM matches_clean
WHERE result = 'win';
""")

   decisive_matches  toss_winner_won    pct
0              1187              613  51.64

In [38]:
# what do captions actually choose when they win the toss?

q("""
SELECT
    COUNT(*) AS decisive_matches,
    toss_decision,
    ROUND(
        100.0 * COUNT() / (SELECT COUNT() FROM matches_clean),
        2   
    ) AS pct
FROM matches_clean
GROUP BY toss_decision;""")

   decisive_matches toss_decision    pct
0               412           bat  33.99
1               800         field  66.01

In [39]:
# which team wins the toss most often?

q("""
SELECT
    toss_winner,
    COUNT(*) AS toss_won
FROM matches_clean
GROUP BY toss_winner
ORDER BY toss_won DESC;
""")

                    toss_winner  toss_won
0                Mumbai Indians       156
1                Delhi Capitals       145
2           Sunrisers Hyderabad       139
3              Rajasthan Royals       134
4   Royal Challengers Bangalore       132
5         Kolkata Knight Riders       132
6           Chennai Super Kings       130
7                  Punjab Kings       126
8                Gujarat Titans        33
9          Lucknow Super Giants        29
10                Pune Warriors        20
11                Gujarat Lions        15
12       Rising Pune Supergiant        13
13         Kochi Tuskers Kerala         8

In [40]:
# what is the average score of first innings runs

q("""
SELECT ROUND(AVG(first_innings_runs), 2) AS average_first_innings_runs
FROM v_match_totals;
""")

   average_first_innings_runs
0                      168.19

In [41]:
q(""" SELECT * FROM v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [42]:
# do chasing teams score faster than teams batting first?

q("""
  SELECT innings,
  ROUND (6.0*SUM(total_runs)/SUM(is_legal),2) AS run_rate
  FROM v_ball
  WHERE innings IN(1,2)
  GROUP BY innings;""")

   innings  run_rate
0        1      8.49
1        2      8.37

In [43]:
# do teams lose more wickets in 1 or 2 innings?
q("""
  SELECT innings,
  ROUND (100.0*SUM(bowler_wicket)/SUM(is_legal),2) AS wicket_rate
  FROM v_ball
  WHERE innings IN(1,2)
  GROUP BY innings;""")

   innings  wicket_rate
0        1         4.69
1        2         4.77

In [44]:
q("""
SELECT
    COUNT(*) AS match_with_200plus,
    SUM(chase_won) AS successfully_chased 

    FROM v_match_totals
    WHERE first_innings_runs >=200;
    
""")

   match_with_200plus  successfully_chased
0                 198                   46

In [45]:
q("""
SELECT
    MAX(CASE WHEN chase_won = 0 THEN first_innings_runs END) AS biggest_defend,
    MAX(CASE WHEN chase_won = 1 THEN first_innings_runs END) AS biggest_chased
FROM v_match_totals;
""")

   biggest_defend  biggest_chased
0             287             264

In [46]:
q("""SELECT m.venue_clean,
       COUNT(DISTINCT m.match_id) AS matches,
       ROUND(AVG(i.runs), 2) AS avg_score
FROM matches_clean m
JOIN v_innings i ON i.match_id = m.match_id
GROUP BY m.venue_clean
HAVING matches >= 25
ORDER BY avg_score DESC
LIMIT 10;""")

                                         venue_clean  matches  avg_score
0                               Arun Jaitley Stadium       41     180.04
1                              Narendra Modi Stadium       37     177.82
2                                  Brabourne Stadium       27     172.31
3       Punjab Cricket Association IS Bindra Stadium       26     170.71
4  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26     167.59
5                                   Wankhede Stadium      130     166.95
6                              M Chinnaswamy Stadium       89     164.79
7                             Sawai Mansingh Stadium       66     161.11
8                 Rajiv Gandhi International Stadium       87     161.06
9                                       Eden Gardens      104     160.94

In [47]:
q("""
SELECT
    match_winner AS team,
    COUNT(*) AS wins
FROM matches_clean
WHERE result = 'win'
GROUP BY match_winner
ORDER BY wins DESC
LIMIT 5;
""")

                          team  wins
0               Mumbai Indians   153
1          Chennai Super Kings   145
2  Royal Challengers Bangalore   138
3        Kolkata Knight Riders   136
4          Sunrisers Hyderabad   128

In [48]:
q("""
SELECT
    batting_team AS team,
    SUM(total_runs) AS powerplay_runs,
    SUM(is_legal) AS legal_balls,
    ROUND(6.0*SUM(total_runs)/SUM(is_legal),2) AS run_rate
FROM v_ball
WHERE phase = 'Powerplay'
GROUP BY batting_team
HAVING legal_balls>3000
ORDER BY run_rate DESC
LIMIT 10;
""")

                          team  powerplay_runs  legal_balls  run_rate
0                 Punjab Kings           13344         9755      8.21
1          Sunrisers Hyderabad           13712        10034      8.20
2             Rajasthan Royals           11797         8768      8.07
3               Delhi Capitals           13237         9893      8.03
4        Kolkata Knight Riders           13016         9738      8.02
5               Mumbai Indians           13561        10257      7.93
6  Royal Challengers Bangalore           13196        10008      7.91
7          Chennai Super Kings           12198         9324      7.85

In [49]:
# which team relies most on boundaries for its runs?

q("""
SELECT 
    batting_team AS team,
    SUM(CASE WHEN batter_runs IN(4,6) THEN batter_runs ELSE 0 END) AS boundaries,
    ROUND(
            100.0 * SUM(CASE WHEN batter_runs IN (4, 6) THEN batter_runs ELSE 0 END)
            /SUM(batter_runs),
            2
        ) AS boundary_run_percentage
FROM v_ball
GROUP BY batting_team
HAVING SUM(is_legal)>=10000
ORDER BY boundary_run_percentage DESC
LIMIT 10;""")

                          team  boundaries  boundary_run_percentage
0               Mumbai Indians       27486                    62.30
1        Kolkata Knight Riders       24846                    61.84
2                 Punjab Kings       25986                    61.67
3  Royal Challengers Bangalore       26220                    61.44
4             Rajasthan Royals       22718                    60.90
5               Delhi Capitals       24688                    59.97
6          Chennai Super Kings       24186                    59.80
7          Sunrisers Hyderabad       24982                    58.50

In [50]:
# which player has won the most player of hte match awards?

q("""
SELECT
    player_of_match AS player,
    COUNT(*) AS MVP_count
FROM matches_clean
GROUP BY player_of_match
ORDER by MVP_count DESC
LIMIT 10;""")

           player  MVP_count
0  AB de Villiers         25
1        CH Gayle         22
2       RG Sharma         21
3         V Kohli         20
4        MS Dhoni         18
5       DA Warner         18
6       SP Narine         17
7       RA Jadeja         17
8        KL Rahul         17
9       YK Pathan         16

In [51]:
# how does the way batters get out change across the phases?

q("""
SELECT
    phase,
    wicket_kind,
    COUNT(*) AS N
FROM v_ball
WHERE is_wicket = 1 AND wicket_kind IN('caught','bowled','run out')
GROUP BY phase,wicket_kind
ORDER BY phase,N DESC;"""

    
)

       phase wicket_kind     N
0      Death      caught  3289
1      Death      bowled   877
2      Death     run out   634
3     Middle      caught  3484
4     Middle      bowled   909
5     Middle     run out   344
6  Powerplay      caught  2272
7  Powerplay      bowled   612
8  Powerplay     run out   189

In [52]:
q("""
SELECT
    player_out AS player_name,
    COUNT(*) AS run_out 
FROM v_ball
WHERE is_wicket = 1 AND wicket_kind IN('run out')
GROUP BY player_out
ORDER BY run_out DESC
LIMIT 10;""")

       player_name  run_out
0         S Dhawan       16
1        G Gambhir       16
2         SK Raina       15
3       KD Karthik       15
4        AT Rayudu       15
5   AB de Villiers       14
6          M Vijay       12
7     F du Plessis       12
8        YK Pathan       11
9  Y Venugopal Rao       11

In [53]:
q(""" SELECT * FROM matches_clean;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_winner,toss_decision,team1,team2
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field,Royal Challengers Bangalore,Kolkata Knight Riders
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field,Sunrisers Hyderabad,Royal Challengers Bangalore
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field,Rising Pune Supergiant,Mumbai Indians
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field,Gujarat Lions,Kolkata Knight Riders
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,Punjab Kings,field,Punjab Kings,Rising Pune Supergiant
...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field,Delhi Capitals,Royal Challengers Bangalore
1208,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,Rajasthan Royals,field,Punjab Kings,Rajasthan Royals
1209,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat,Mumbai Indians,Sunrisers Hyderabad
1210,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,Gujarat Titans,field,Royal Challengers Bangalore,Gujarat Titans
1211,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat,Rajasthan Royals,Delhi Capitals

In [54]:
#how many matches were played each season?

q("""
SELECT
    season_year AS season,
    COUNT(*) AS matches_count
FROM matches_clean
GROUP BY season_year
ORDER BY matches_count DESC;""")

    season  matches_count
0     2013             76
1     2025             74
2     2023             74
3     2022             74
4     2012             74
5     2011             73
6     2024             71
7     2021             60
8     2020             60
9     2019             60
10    2018             60
11    2016             60
12    2014             60
13    2010             60
14    2017             59
15    2015             59
16    2008             58
17    2009             57
18    2026             43

In [55]:
# which bowler dismissed a batter most otfen?

q("""
SELECT
    bowler,
    player_out AS batter,
    COUNT(*) AS times_out
FROM v_ball
WHERE bowler_wicket = 1
GROUP BY bowler,batter
ORDER BY times_out DESC
LIMIT 20;"""

    )

            bowler      batter  times_out
0        SP Narine   RG Sharma          8
1         A Mishra   RG Sharma          7
2          B Kumar   AM Rahane          7
3        JJ Bumrah     RR Pant          7
4        MM Sharma   AT Rayudu          7
5         R Ashwin  RV Uthappa          7
6   Sandeep Sharma     V Kohli          7
7        YS Chahal  MA Agarwal          7
8           Z Khan    MS Dhoni          7
9         A Mishra   SR Watson          6
10         A Nehra     V Kohli          6
11        AR Patel   SR Watson          6
12         B Kumar    PA Patel          6
13       DL Chahar     PP Shaw          6
14       PP Chawla   AT Rayudu          6
15         PP Ojha    MS Dhoni          6
16        R Ashwin   AM Rahane          6
17   R Vinay Kumar   RG Sharma          6
18       RA Jadeja  GJ Maxwell          6
19  Sandeep Sharma   RG Sharma          6

In [56]:
# find an opener who scores fast AND survives the powerplay

q("""
SELECT
    batter,
    SUM(is_legal) AS balls,
    ROUND(100.0*SUM(batter_runs)/SUM(is_legal),2) AS strike_rate,
    SUM(batter_runs) AS runs
FROM v_ball
WHERE phase='Powerplay' AND is_wicket=0
GROUP BY batter
HAVING balls>=500
ORDER BY strike_rate DESC
LIMIT 10;""" 
)

            batter  balls  strike_rate  runs
0        SP Narine    640       183.44  1174
1  Abhishek Sharma    712       180.76  1287
2      YBK Jaiswal    948       166.56  1579
3   P Simran Singh    658       162.61  1070
4      JM Bairstow    601       157.07   944
5          PP Shaw    866       155.54  1347
6         V Sehwag   1036       153.76  1593
7          CA Lynn    520       149.81   779
8      RA Tripathi    685       147.88  1013
9       JC Buttler   1216       147.04  1788

In [57]:
# find a genuine all-rounder : 1000+ runs and 50+ wickets

q("""
SELECT
    b.batter AS player,
    SUM(b.batter_runs) AS runs,
    (SELECT SUM(x.bowler_wicket) FROM v_ball x
    WHERE x.bowler=b.batter) AS wickets
FROM v_ball b
GROUP BY b.batter
HAVING runs>=1000 AND wickets>=50
ORDER BY runs DESC
LIMIT 10;""")

       player  runs  wickets
0   SR Watson  3874       92
1  KA Pollard  3412       69
2   RA Jadeja  3412      177
3   HH Pandya  2877       82
4  AD Russell  2651      123
5   JH Kallis  2427       65
6    AR Patel  1947      136
7   SP Narine  1820      199
8   KH Pandya  1796      102
9    DJ Bravo  1560      183

In [58]:
# who performs best when chasing at the death?

q("""
SELECT 
    batter,
    SUM(is_legal) AS balls,
        ROUND(100.0*SUM(batter_runs)/SUM(is_legal),2) AS strike_rate,
        SUM(batter_runs) AS runs
FROM v_ball
WHERE phase='Death' AND innings=2
GROUP BY batter
HAVING balls>200
ORDER BY strike_rate DESC
LIMIT 10;""")

           batter  balls  strike_rate  runs
0  AB de Villiers    295       209.83   619
1         SS Iyer    215       187.44   403
2       DA Miller    439       186.33   818
3         RR Pant    214       185.51   397
4       SV Samson    207       183.57   380
5      KA Pollard    429       183.45   787
6      SO Hetmyer    217       180.65   392
7         V Kohli    336       180.65   607
8      AD Russell    265       174.72   463
9       YK Pathan    331       174.32   577

In [60]:
q("""
SELECT COUNT(*) AS wins FROM matches_clean WHERE match_winner = 'Mumbai Indians';""")

   wins
0   155