In [1]:
import sqlite3
import pandas as pd

con=sqlite3.connect('C:\\Users\\muhju\\Downloads\\sem 3 ojt\\proj 3.1\\data\\raw\\ipl.db')
def q(sql):
    return pd.read_sql(sql, con)

In [2]:
q(""" select * from venues ;""")

,venue_id,venue,city
0,1,M Chinnaswamy Stadium,Bangalore
1,2,"Rajiv Gandhi International Stadium, Uppal",Hyderabad
2,3,Maharashtra Cricket Association Stadium,Pune
3,4,Saurashtra Cricket Association Stadium,Rajkot
4,5,Holkar Cricket Stadium,Indore
...,...,...,...
58,59,Subrata Roy Sahara Stadium,Pune
59,60,Shaheed Veer Narayan Singh International Stadium,Raipur
60,61,JSCA International Stadium Complex,Ranchi
61,62,Maharaja Yadavindra Singh International Cricke...,New Chandigarh
62,63,Maharaja Yadavindra Singh International Cricke...,New Chandigarh

In [3]:
q("""select * from matches;""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,9.0,win,JR Hazlewood,252,1,1,1,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Rajasthan Royals,NaN,6.0,win,D Ferreira,494,134,134,134,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,6.0,win,H Klaasen,3,2,3,2,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,Gujarat Titans,NaN,4.0,win,JO Holder,1,615,615,615,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,Delhi Capitals,NaN,7.0,win,KL Rahul,134,252,134,252,1409.0

In [4]:
q("""select * from venues;""")

,venue_id,venue,city
0,1,M Chinnaswamy Stadium,Bangalore
1,2,"Rajiv Gandhi International Stadium, Uppal",Hyderabad
2,3,Maharashtra Cricket Association Stadium,Pune
3,4,Saurashtra Cricket Association Stadium,Rajkot
4,5,Holkar Cricket Stadium,Indore
...,...,...,...
58,59,Subrata Roy Sahara Stadium,Pune
59,60,Shaheed Veer Narayan Singh International Stadium,Raipur
60,61,JSCA International Stadium Complex,Ranchi
61,62,Maharaja Yadavindra Singh International Cricke...,New Chandigarh
62,63,Maharaja Yadavindra Singh International Cricke...,New Chandigarh

In [5]:
q("""select * from deliveries;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,1,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,0,0,NaN,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288221,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288222,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288223,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288224,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals
288225,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,0,0,NaN,0,2,252,134,Delhi Capitals,Rajasthan Royals

In [6]:
q("""select * from teams;""")

    team_id                    team_name
0         1  Royal Challengers Bangalore
1         2          Sunrisers Hyderabad
2         3               Mumbai Indians
3         4       Rising Pune Supergiant
4         5                Gujarat Lions
5         6        Kolkata Knight Riders
6       129          Chennai Super Kings
7       134             Rajasthan Royals
8       252               Delhi Capitals
9       494                 Punjab Kings
10      614         Lucknow Super Giants
11      615               Gujarat Titans
12     1068              Deccan Chargers
13     1414         Kochi Tuskers Kerala
14     1419                Pune Warriors
15     3604      Rising Pune Supergiants

In [7]:
q("""select * from players;""")

,player_id,player_name,bat_style,bowl_style,field_pos,player_full_name
0,963,MN Samuels,Right hand Bat,Right arm Offbreak,,Marlon Nathaniel Samuels
1,53,SB Jakati,Left hand Bat,Slow Left arm Orthodox,,Shadab Bashir Jakati
2,12,DA Warner,Left hand Bat,Legbreak,,David Andrew Warner
3,268,RA Tripathi,Right hand Bat,Right arm Medium,,Rahul Ajay Tripathi
4,186,S Nadeem,Right hand Bat,Slow Left arm Orthodox,,Shahbaz Nadeem
...,...,...,...,...,...,...
794,8475,Suyash Sharma,Right hand Bat,Legbreak Googly,,Suyash Sharma
795,45004,D Madushanka,Right hand Bat,Right arm Medium fast,NaN,K Dasun Madusanka
796,42566,V Suryavanshi,Left hand Bat,Slow Left arm Orthodox,NaN,Vaibhav Suryavanshi
797,26,N Rana,Left hand Bat,"Right arm Medium, Right arm Offbreak, Legbreak",,Nitish Rana
798,45986,SU Parakh,Left hand Bat,Legbreak,NaN,Sahil Ulhas Parakh

In [8]:
q("""select * 
from matches limit 10;""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
5,1082595,2017,6,Bengaluru,2017-04-08,Indian Premier League,5.0,male,T20,T20,...,Royal Challengers Bangalore,15.0,NaN,win,KM Jadhav,1,252,1,1,4.0
6,1082596,2017,6,Hyderabad,2017-04-09,Indian Premier League,6.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,9.0,win,Rashid Khan,2,5,2,2,22.0
7,1082597,2017,6,Mumbai,2017-04-09,Indian Premier League,7.0,male,T20,T20,...,Mumbai Indians,NaN,4.0,win,N Rana,3,6,3,3,26.0
8,1082598,2017,6,Indore,2017-04-10,Indian Premier League,8.0,male,T20,T20,...,Punjab Kings,NaN,8.0,win,AR Patel,494,1,1,494,70.0
9,1082599,2017,6,Pune,2017-04-11,Indian Premier League,9.0,male,T20,T20,...,Delhi Capitals,97.0,NaN,win,SV Samson,4,252,4,252,180.0

In [9]:
q("""select match_id,city,venue
from matches limit 15;""")

    match_id       city                                      venue
0     335982  Bangalore                      M Chinnaswamy Stadium
1    1082591  Hyderabad  Rajiv Gandhi International Stadium, Uppal
2    1082592       Pune    Maharashtra Cricket Association Stadium
3    1082593     Rajkot     Saurashtra Cricket Association Stadium
4    1082594     Indore                     Holkar Cricket Stadium
5    1082595  Bengaluru                      M.Chinnaswamy Stadium
6    1082596  Hyderabad  Rajiv Gandhi International Stadium, Uppal
7    1082597     Mumbai                           Wankhede Stadium
8    1082598     Indore                     Holkar Cricket Stadium
9    1082599       Pune    Maharashtra Cricket Association Stadium
10   1082600     Mumbai                           Wankhede Stadium
11   1082601    Kolkata                               Eden Gardens
12   1082602  Bangalore                      M Chinnaswamy Stadium
13   1082603     Rajkot     Saurashtra Cricket Association Stadium
14   1082604    Kolkata                               Eden Gardens

In [10]:
q("""select match_id,batter,bowler,non_striker,over_number from deliveries limit 10; """)

   match_id       batter   bowler  non_striker  over_number
0    335982   SC Ganguly  P Kumar  BB McCullum            0
1    335982  BB McCullum  P Kumar   SC Ganguly            0
2    335982  BB McCullum  P Kumar   SC Ganguly            0
3    335982  BB McCullum  P Kumar   SC Ganguly            0
4    335982  BB McCullum  P Kumar   SC Ganguly            0
5    335982  BB McCullum  P Kumar   SC Ganguly            0
6    335982  BB McCullum  P Kumar   SC Ganguly            0
7    335982  BB McCullum   Z Khan   SC Ganguly            1
8    335982  BB McCullum   Z Khan   SC Ganguly            1
9    335982  BB McCullum   Z Khan   SC Ganguly            1

In [11]:
q("""select distinct city from venues; """)

              city
0        Bangalore
1        Hyderabad
2             Pune
3           Rajkot
4           Indore
5        Bengaluru
6           Mumbai
7          Kolkata
8            Delhi
9       Chandigarh
10          Kanpur
11         Chennai
12          Jaipur
13   Visakhapatnam
14       Abu Dhabi
15             NaN
16       Ahmedabad
17         Sharjah
18           Dubai
19     Navi Mumbai
20         Lucknow
21        Guwahati
22      Dharamsala
23          Mohali
24       Cape Town
25  Port Elizabeth
26          Durban
27       Centurion
28     East London
29    Johannesburg
30       Kimberley
31    Bloemfontein
32         Cuttack
33          Nagpur
34           Kochi
35          Raipur
36          Ranchi
37  New Chandigarh

In [12]:
q("""select distinct batsman_type from deliveries; """)

     batsman_type
0   Left hand Bat
1  Right hand Bat
2             NaN

In [13]:
q("""select distinct season from matches; """)

     season
0      2008
1      2009
2      2010
3      2011
4      2012
5      2013
6      2014
7      2015
8      2016
9      2017
10     2018
11     2019
12  2020/21
13     2021
14     2022
15     2023
16     2024
17     2025
18     2026

In [14]:
q("""select match_id,season_id,city,venue
from matches
where season > 2015;""")

,match_id,season_id,city,venue
0,980901,2016,Mumbai,Wankhede Stadium
1,980903,2016,Kolkata,Eden Gardens
2,980905,2016,Chandigarh,"Punjab Cricket Association IS Bindra Stadium, ..."
3,980907,2016,Bangalore,M Chinnaswamy Stadium
4,980909,2016,Kolkata,Eden Gardens
...,...,...,...,...
690,1529282,2026,Delhi,"Arun Jaitley Stadium, Delhi"
691,1529283,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
692,1529284,2026,Mumbai,"Wankhede Stadium, Mumbai"
693,1529285,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
694,1529286,2026,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [15]:
q("""select match_id,season_id,city,venue
from matches
where season >= 2015 and city = 'Mumbai';""")

     match_id  season_id    city                     venue
0      829717       2015  Mumbai          Wankhede Stadium
1      829729       2015  Mumbai          Wankhede Stadium
2      829751       2015  Mumbai          Wankhede Stadium
3      829769       2015  Mumbai          Wankhede Stadium
4      829777       2015  Mumbai         Brabourne Stadium
..        ...        ...     ...                       ...
118   1527675       2026  Mumbai  Wankhede Stadium, Mumbai
119   1527693       2026  Mumbai  Wankhede Stadium, Mumbai
120   1529267       2026  Mumbai  Wankhede Stadium, Mumbai
121   1529276       2026  Mumbai  Wankhede Stadium, Mumbai
122   1529284       2026  Mumbai  Wankhede Stadium, Mumbai

[123 rows x 4 columns]

In [16]:
q("""select match_id,season_id,city,venue
from matches
where season >= 2015 or city = 'Mumbai';""")

,match_id,season_id,city,venue
0,1082591,2017,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
1,1082592,2017,Pune,Maharashtra Cricket Association Stadium
2,1082593,2017,Rajkot,Saurashtra Cricket Association Stadium
3,1082594,2017,Indore,Holkar Cricket Stadium
4,1082595,2017,Bengaluru,M.Chinnaswamy Stadium
...,...,...,...,...
811,1529282,2026,Delhi,"Arun Jaitley Stadium, Delhi"
812,1529283,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
813,1529284,2026,Mumbai,"Wankhede Stadium, Mumbai"
814,1529285,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
815,1529286,2026,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [17]:
q("""select match_id from matches
order by match_id ;""")

      match_id
0       335982
1       335983
2       335984
3       335985
4       335986
...        ...
1207   1529282
1208   1529283
1209   1529284
1210   1529285
1211   1529286

[1212 rows x 1 columns]

In [18]:
q("""select match_id from matches
order by match_id ASC;""")

      match_id
0       335982
1       335983
2       335984
3       335985
4       335986
...        ...
1207   1529282
1208   1529283
1209   1529284
1210   1529285
1211   1529286

[1212 rows x 1 columns]

In [19]:
q("""select match_id from matches
order by match_id DESC;""")

      match_id
0      1529286
1      1529285
2      1529284
3      1529283
4      1529282
...        ...
1207    335986
1208    335985
1209    335984
1210    335983
1211    335982

[1212 rows x 1 columns]

In [20]:
q("""select city from matches
order by city ASC;""")

               city
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
1207  Visakhapatnam
1208  Visakhapatnam
1209  Visakhapatnam
1210  Visakhapatnam
1211  Visakhapatnam

[1212 rows x 1 columns]

In [21]:
q("""select city from matches
order by city DESC;""")

               city
0     Visakhapatnam
1     Visakhapatnam
2     Visakhapatnam
3     Visakhapatnam
4     Visakhapatnam
...             ...
1207            NaN
1208            NaN
1209            NaN
1210            NaN
1211            NaN

[1212 rows x 1 columns]

In [22]:
q(""" SELECT COUNT(*) AS matches
FROM matches;""")

   matches
0     1212

In [23]:
q(""" SELECT DISTINCT venue
FROM matches;""")

                                                venue
0                               M Chinnaswamy Stadium
1           Rajiv Gandhi International Stadium, Uppal
2             Maharashtra Cricket Association Stadium
3              Saurashtra Cricket Association Stadium
4                              Holkar Cricket Stadium
5                               M.Chinnaswamy Stadium
6                                    Wankhede Stadium
7                                        Eden Gardens
8                                    Feroz Shah Kotla
9   Punjab Cricket Association IS Bindra Stadium, ...
10                                         Green Park
11       Punjab Cricket Association IS Bindra Stadium
12                 Rajiv Gandhi International Stadium
13                             MA Chidambaram Stadium
14                             Sawai Mansingh Stadium
15                               Arun Jaitley Stadium
16  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
17                               Sheikh Zayed Stadium
18                Dubai International Cricket Stadium
19                            Sharjah Cricket Stadium
20           MA Chidambaram Stadium, Chepauk, Chennai
21                           Wankhede Stadium, Mumbai
22                   Narendra Modi Stadium, Ahmedabad
23                        Arun Jaitley Stadium, Delhi
24                   Zayed Cricket Stadium, Abu Dhabi
25                          Brabourne Stadium, Mumbai
26                 Dr DY Patil Sports Academy, Mumbai
27      Maharashtra Cricket Association Stadium, Pune
28                              Eden Gardens, Kolkata
29  Punjab Cricket Association IS Bindra Stadium, ...
30  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
31  Rajiv Gandhi International Stadium, Uppal, Hyd...
32                   M Chinnaswamy Stadium, Bengaluru
33                Barsapara Cricket Stadium, Guwahati
34                     Sawai Mansingh Stadium, Jaipur
35  Himachal Pradesh Cricket Association Stadium, ...
36  Maharaja Yadavindra Singh International Cricke...
37  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
38         Punjab Cricket Association Stadium, Mohali
39                    MA Chidambaram Stadium, Chepauk
40                         Dr DY Patil Sports Academy
41                                           Newlands
42                                   St George's Park
43                                          Kingsmead
44                                    SuperSport Park
45                                       Buffalo Park
46                              New Wanderers Stadium
47                              De Beers Diamond Oval
48                                    OUTsurance Oval
49                                  Brabourne Stadium
50                       Sardar Patel Stadium, Motera
51                                   Barabati Stadium
52       Vidarbha Cricket Association Stadium, Jamtha
53       Himachal Pradesh Cricket Association Stadium
54                                      Nehru Stadium
55                         Subrata Roy Sahara Stadium
56   Shaheed Veer Narayan Singh International Stadium
57                 JSCA International Stadium Complex
58  Maharaja Yadavindra Singh International Cricke...

In [24]:
q(""" SELECT COUNT(DISTINCT venue) AS venues
FROM matches;""")

   venues
0      59

In [25]:
q(""" SELECT COUNT(*) AS deliveries
FROM deliveries;""")

   deliveries
0      288226

In [26]:
q(""" SELECT COUNT(*) AS players
FROM players;""")

   players
0      799

In [27]:
q(""" SELECT COUNT(*) AS teams
FROM teams;""")

   teams
0     16

In [28]:
q(""" SELECT venue, COUNT(*) AS matches
FROM matches
GROUP BY venue ORDER BY matches DESC;""")

                                                venue  matches
0                                        Eden Gardens       77
1                                    Wankhede Stadium       73
2                               M Chinnaswamy Stadium       65
3                                    Feroz Shah Kotla       60
4                            Wankhede Stadium, Mumbai       57
5           Rajiv Gandhi International Stadium, Uppal       49
6                     MA Chidambaram Stadium, Chepauk       48
7                              Sawai Mansingh Stadium       47
8                 Dubai International Cricket Stadium       46
9            MA Chidambaram Stadium, Chepauk, Chennai       38
10                   Narendra Modi Stadium, Ahmedabad       37
11         Punjab Cricket Association Stadium, Mohali       35
12                               Sheikh Zayed Stadium       29
13                            Sharjah Cricket Stadium       28
14                              Eden Gardens, Kolkata       27
15                        Arun Jaitley Stadium, Delhi       27
16  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26
17                   M Chinnaswamy Stadium, Bengaluru       24
18  Rajiv Gandhi International Stadium, Uppal, Hyd...       23
19            Maharashtra Cricket Association Stadium       22
20                 Dr DY Patil Sports Academy, Mumbai       20
21                     Sawai Mansingh Stadium, Jaipur       19
22                         Dr DY Patil Sports Academy       17
23                          Brabourne Stadium, Mumbai       17
24                         Subrata Roy Sahara Stadium       16
25                 Rajiv Gandhi International Stadium       15
26                              M.Chinnaswamy Stadium       15
27                                          Kingsmead       15
28                               Arun Jaitley Stadium       14
29      Maharashtra Cricket Association Stadium, Pune       13
30  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       13
31                                    SuperSport Park       12
32                       Sardar Patel Stadium, Motera       12
33  Punjab Cricket Association IS Bindra Stadium, ...       11
34             Saurashtra Cricket Association Stadium       10
35       Punjab Cricket Association IS Bindra Stadium       10
36  Maharaja Yadavindra Singh International Cricke...       10
37                                  Brabourne Stadium       10
38                             MA Chidambaram Stadium        9
39                             Holkar Cricket Stadium        9
40       Himachal Pradesh Cricket Association Stadium        9
41                   Zayed Cricket Stadium, Abu Dhabi        8
42                              New Wanderers Stadium        8
43                Barsapara Cricket Stadium, Guwahati        8
44                                   St George's Park        7
45                                           Newlands        7
46                 JSCA International Stadium Complex        7
47                                   Barabati Stadium        7
48   Shaheed Veer Narayan Singh International Stadium        6
49  Himachal Pradesh Cricket Association Stadium, ...        6
50  Punjab Cricket Association IS Bindra Stadium, ...        5
51                                      Nehru Stadium        5
52  Maharaja Yadavindra Singh International Cricke...        5
53                                         Green Park        4
54  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        4
55       Vidarbha Cricket Association Stadium, Jamtha        3
56                              De Beers Diamond Oval        3
57                                       Buffalo Park        3
58                                    OUTsurance Oval        2

In [29]:
q(""" SELECT match_winner, COUNT(*) AS wins
FROM matches
GROUP BY match_winner ORDER BY wins DESC;""")

                   match_winner  wins
0                Mumbai Indians   155
1           Chennai Super Kings   146
2   Royal Challengers Bangalore   139
3         Kolkata Knight Riders   137
4           Sunrisers Hyderabad   132
5                  Punjab Kings   130
6                Delhi Capitals   126
7              Rajasthan Royals   125
8                Gujarat Titans    42
9          Lucknow Super Giants    33
10       Rising Pune Supergiant    15
11                Pune Warriors    13
12                Gujarat Lions    13
13         Kochi Tuskers Kerala     6

In [30]:
q(""" SELECT match_winner, COUNT(*) AS wins
FROM matches
GROUP BY match_winner HAVING COUNT(*) >= 100
ORDER BY wins DESC;""")

                  match_winner  wins
0               Mumbai Indians   155
1          Chennai Super Kings   146
2  Royal Challengers Bangalore   139
3        Kolkata Knight Riders   137
4          Sunrisers Hyderabad   132
5                 Punjab Kings   130
6               Delhi Capitals   126
7             Rajasthan Royals   125

In [31]:
q(""" SELECT bowler, COUNT(*) AS deliveries
FROM deliveries
GROUP BY bowler HAVING COUNT(*) >= 1000
ORDER BY deliveries DESC;""")

          bowler  deliveries
0       R Ashwin        4868
1        B Kumar        4596
2      SP Narine        4586
3      RA Jadeja        4261
4      YS Chahal        4068
..           ...         ...
81      VR Aaron        1065
82    GJ Maxwell        1047
83  JR Hazlewood        1035
84    Noor Ahmad        1008
85       S Gopal        1000

[86 rows x 2 columns]

In [32]:
q(""" SELECT COUNT(*) AS nullvalues
FROM matches
WHERE city IS NULL;""")

   nullvalues
0          51

In [33]:
q(""" SELECT COUNT(*) AS count_of_teams_won_by_runs
FROM matches
WHERE win_by_runs IS NOT NULL;""")

   count_of_teams_won_by_runs
0                         546

In [34]:
q(""" SELECT match_winner, COUNT(*) AS no_of_wins_by_runs
FROM matches
WHERE win_by_runs IS NOT NULL
GROUP BY match_winner
ORDER BY no_of_wins_by_runs DESC;""")

                   match_winner  no_of_wins_by_runs
0                Mumbai Indians                  77
1           Chennai Super Kings                  75
2           Sunrisers Hyderabad                  69
3   Royal Challengers Bangalore                  64
4                  Punjab Kings                  57
5         Kolkata Knight Riders                  57
6              Rajasthan Royals                  48
7                Delhi Capitals                  47
8          Lucknow Super Giants                  20
9                Gujarat Titans                  16
10       Rising Pune Supergiant                   7
11                Pune Warriors                   6
12         Kochi Tuskers Kerala                   2
13                Gujarat Lions                   1

In [35]:
q(""" SELECT batter,bowler
FROM deliveries
WHERE is_wicket =1;""")

           batter        bowler
0      SC Ganguly        Z Khan
1      RT Ponting     JH Kallis
2       DJ Hussey     AA Noffke
3        R Dravid      I Sharma
4         V Kohli      AB Dinda
...           ...           ...
14335     R Parag      MA Starc
14336    SB Dubey   T Natarajan
14337  P Nissanka     RA Jadeja
14338      N Rana  TU Deshpande
14339    KL Rahul     JC Archer

[14340 rows x 2 columns]

In [36]:
q(""" SELECT LOWER(batter)
FROM deliveries;""")

         LOWER(batter)
0       a ashish reddy
1       a ashish reddy
2       a ashish reddy
3       a ashish reddy
4       a ashish reddy
...                ...
288221          z khan
288222          z khan
288223          z khan
288224          z khan
288225          z khan

[288226 rows x 1 columns]

In [37]:
q(""" SELECT TRIM("    nihad minshn   ");""")

  TRIM("    nihad minshn   ")
0                nihad minshn

In [38]:
q(""" SELECT city,LENGTH(city)
FROM venues;""")

              city  LENGTH(city)
0        Bangalore           9.0
1        Hyderabad           9.0
2             Pune           4.0
3           Rajkot           6.0
4           Indore           6.0
..             ...           ...
58            Pune           4.0
59          Raipur           6.0
60          Ranchi           6.0
61  New Chandigarh          14.0
62  New Chandigarh          14.0

[63 rows x 2 columns]

In [39]:
q(""" SELECT match_winner,
CASE 
WHEN win_by_runs IS NULL THEN 'win by wickets'
ELSE 'win by runs'
END AS win_type
FROM matches;""")

                     match_winner        win_type
0           Kolkata Knight Riders     win by runs
1             Sunrisers Hyderabad     win by runs
2          Rising Pune Supergiant  win by wickets
3           Kolkata Knight Riders  win by wickets
4                    Punjab Kings  win by wickets
...                           ...             ...
1207  Royal Challengers Bangalore  win by wickets
1208             Rajasthan Royals  win by wickets
1209          Sunrisers Hyderabad  win by wickets
1210               Gujarat Titans  win by wickets
1211               Delhi Capitals  win by wickets

[1212 rows x 2 columns]

In [40]:
q("""SELECT venue,count(*) as matches
from matches
group by venue;""")

                                                venue  matches
0                                Arun Jaitley Stadium       14
1                         Arun Jaitley Stadium, Delhi       27
2                                    Barabati Stadium        7
3                 Barsapara Cricket Stadium, Guwahati        8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26
5                                   Brabourne Stadium       10
6                           Brabourne Stadium, Mumbai       17
7                                        Buffalo Park        3
8                               De Beers Diamond Oval        3
9                          Dr DY Patil Sports Academy       17
10                 Dr DY Patil Sports Academy, Mumbai       20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        4
13                Dubai International Cricket Stadium       46
14                                       Eden Gardens       77
15                              Eden Gardens, Kolkata       27
16                                   Feroz Shah Kotla       60
17                                         Green Park        4
18       Himachal Pradesh Cricket Association Stadium        9
19  Himachal Pradesh Cricket Association Stadium, ...        6
20                             Holkar Cricket Stadium        9
21                 JSCA International Stadium Complex        7
22                                          Kingsmead       15
23                              M Chinnaswamy Stadium       65
24                   M Chinnaswamy Stadium, Bengaluru       24
25                              M.Chinnaswamy Stadium       15
26                             MA Chidambaram Stadium        9
27                    MA Chidambaram Stadium, Chepauk       48
28           MA Chidambaram Stadium, Chepauk, Chennai       38
29  Maharaja Yadavindra Singh International Cricke...       10
30  Maharaja Yadavindra Singh International Cricke...        5
31            Maharashtra Cricket Association Stadium       22
32      Maharashtra Cricket Association Stadium, Pune       13
33                   Narendra Modi Stadium, Ahmedabad       37
34                                      Nehru Stadium        5
35                              New Wanderers Stadium        8
36                                           Newlands        7
37                                    OUTsurance Oval        2
38       Punjab Cricket Association IS Bindra Stadium       10
39  Punjab Cricket Association IS Bindra Stadium, ...       11
40  Punjab Cricket Association IS Bindra Stadium, ...        5
41         Punjab Cricket Association Stadium, Mohali       35
42                 Rajiv Gandhi International Stadium       15
43          Rajiv Gandhi International Stadium, Uppal       49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...       23
45                       Sardar Patel Stadium, Motera       12
46             Saurashtra Cricket Association Stadium       10
47                             Sawai Mansingh Stadium       47
48                     Sawai Mansingh Stadium, Jaipur       19
49   Shaheed Veer Narayan Singh International Stadium        6
50                            Sharjah Cricket Stadium       28
51                               Sheikh Zayed Stadium       29
52                                   St George's Park        7
53                         Subrata Roy Sahara Stadium       16
54                                    SuperSport Park       12
55       Vidarbha Cricket Association Stadium, Jamtha        3
56                                   Wankhede Stadium       73
57                           Wankhede Stadium, Mumbai       57
58                   Zayed Cricket Stadium, Abu Dhabi        8

In [41]:
q("""SELECT venue,count(*) as matches
from matches
where venue='Buffalo Park' OR venue='Barabati Stadium'
group by venue;""")

              venue  matches
0  Barabati Stadium        7
1      Buffalo Park        3

In [42]:
q("""SELECT batter,count(*) as deliveries
from deliveries
group by batter
order by deliveries desc;""")

             batter  deliveries
0           V Kohli        6942
1         RG Sharma        5561
2          S Dhawan        5483
3         DA Warner        4849
4         AM Rahane        4259
..              ...         ...
722     Sunny Gupta           1
723          U Kaul           1
724  V Pratap Singh           1
725   Y Prithvi Raj           1
726      YA Abdulla           1

[727 rows x 2 columns]

In [43]:
q("""select match_winner,
CASE WHEN win_by_runs>50
Then 'High runs'
ELSE 'low runs'
END as runs
from matches;""")

                     match_winner       runs
0           Kolkata Knight Riders  High runs
1             Sunrisers Hyderabad   low runs
2          Rising Pune Supergiant   low runs
3           Kolkata Knight Riders   low runs
4                    Punjab Kings   low runs
...                           ...        ...
1207  Royal Challengers Bangalore   low runs
1208             Rajasthan Royals   low runs
1209          Sunrisers Hyderabad   low runs
1210               Gujarat Titans   low runs
1211               Delhi Capitals   low runs

[1212 rows x 2 columns]

In [44]:
q(""" SELECT season, COUNT(*) AS matches
FROM matches
GROUP BY season;""")

     season  matches
0      2008       58
1      2009       57
2      2010       60
3      2011       73
4      2012       74
5      2013       76
6      2014       60
7      2015       59
8      2016       60
9      2017       59
10     2018       60
11     2019       60
12  2020/21       60
13     2021       60
14     2022       74
15     2023       74
16     2024       71
17     2025       74
18     2026       43

In [45]:
q(""" SELECT venue, COUNT(*) AS matches
FROM matches
GROUP BY venue;""")

                                                venue  matches
0                                Arun Jaitley Stadium       14
1                         Arun Jaitley Stadium, Delhi       27
2                                    Barabati Stadium        7
3                 Barsapara Cricket Stadium, Guwahati        8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26
5                                   Brabourne Stadium       10
6                           Brabourne Stadium, Mumbai       17
7                                        Buffalo Park        3
8                               De Beers Diamond Oval        3
9                          Dr DY Patil Sports Academy       17
10                 Dr DY Patil Sports Academy, Mumbai       20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        4
13                Dubai International Cricket Stadium       46
14                                       Eden Gardens       77
15                              Eden Gardens, Kolkata       27
16                                   Feroz Shah Kotla       60
17                                         Green Park        4
18       Himachal Pradesh Cricket Association Stadium        9
19  Himachal Pradesh Cricket Association Stadium, ...        6
20                             Holkar Cricket Stadium        9
21                 JSCA International Stadium Complex        7
22                                          Kingsmead       15
23                              M Chinnaswamy Stadium       65
24                   M Chinnaswamy Stadium, Bengaluru       24
25                              M.Chinnaswamy Stadium       15
26                             MA Chidambaram Stadium        9
27                    MA Chidambaram Stadium, Chepauk       48
28           MA Chidambaram Stadium, Chepauk, Chennai       38
29  Maharaja Yadavindra Singh International Cricke...       10
30  Maharaja Yadavindra Singh International Cricke...        5
31            Maharashtra Cricket Association Stadium       22
32      Maharashtra Cricket Association Stadium, Pune       13
33                   Narendra Modi Stadium, Ahmedabad       37
34                                      Nehru Stadium        5
35                              New Wanderers Stadium        8
36                                           Newlands        7
37                                    OUTsurance Oval        2
38       Punjab Cricket Association IS Bindra Stadium       10
39  Punjab Cricket Association IS Bindra Stadium, ...       11
40  Punjab Cricket Association IS Bindra Stadium, ...        5
41         Punjab Cricket Association Stadium, Mohali       35
42                 Rajiv Gandhi International Stadium       15
43          Rajiv Gandhi International Stadium, Uppal       49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...       23
45                       Sardar Patel Stadium, Motera       12
46             Saurashtra Cricket Association Stadium       10
47                             Sawai Mansingh Stadium       47
48                     Sawai Mansingh Stadium, Jaipur       19
49   Shaheed Veer Narayan Singh International Stadium        6
50                            Sharjah Cricket Stadium       28
51                               Sheikh Zayed Stadium       29
52                                   St George's Park        7
53                         Subrata Roy Sahara Stadium       16
54                                    SuperSport Park       12
55       Vidarbha Cricket Association Stadium, Jamtha        3
56                                   Wankhede Stadium       73
57                           Wankhede Stadium, Mumbai       57
58                   Zayed Cricket Stadium, Abu Dhabi        8

In [46]:
q(""" SELECT venue, COUNT(*) AS matches
FROM matches
GROUP BY venue
ORDER BY matches DESC;""")

                                                venue  matches
0                                        Eden Gardens       77
1                                    Wankhede Stadium       73
2                               M Chinnaswamy Stadium       65
3                                    Feroz Shah Kotla       60
4                            Wankhede Stadium, Mumbai       57
5           Rajiv Gandhi International Stadium, Uppal       49
6                     MA Chidambaram Stadium, Chepauk       48
7                              Sawai Mansingh Stadium       47
8                 Dubai International Cricket Stadium       46
9            MA Chidambaram Stadium, Chepauk, Chennai       38
10                   Narendra Modi Stadium, Ahmedabad       37
11         Punjab Cricket Association Stadium, Mohali       35
12                               Sheikh Zayed Stadium       29
13                            Sharjah Cricket Stadium       28
14                              Eden Gardens, Kolkata       27
15                        Arun Jaitley Stadium, Delhi       27
16  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26
17                   M Chinnaswamy Stadium, Bengaluru       24
18  Rajiv Gandhi International Stadium, Uppal, Hyd...       23
19            Maharashtra Cricket Association Stadium       22
20                 Dr DY Patil Sports Academy, Mumbai       20
21                     Sawai Mansingh Stadium, Jaipur       19
22                         Dr DY Patil Sports Academy       17
23                          Brabourne Stadium, Mumbai       17
24                         Subrata Roy Sahara Stadium       16
25                 Rajiv Gandhi International Stadium       15
26                              M.Chinnaswamy Stadium       15
27                                          Kingsmead       15
28                               Arun Jaitley Stadium       14
29      Maharashtra Cricket Association Stadium, Pune       13
30  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       13
31                                    SuperSport Park       12
32                       Sardar Patel Stadium, Motera       12
33  Punjab Cricket Association IS Bindra Stadium, ...       11
34             Saurashtra Cricket Association Stadium       10
35       Punjab Cricket Association IS Bindra Stadium       10
36  Maharaja Yadavindra Singh International Cricke...       10
37                                  Brabourne Stadium       10
38                             MA Chidambaram Stadium        9
39                             Holkar Cricket Stadium        9
40       Himachal Pradesh Cricket Association Stadium        9
41                   Zayed Cricket Stadium, Abu Dhabi        8
42                              New Wanderers Stadium        8
43                Barsapara Cricket Stadium, Guwahati        8
44                                   St George's Park        7
45                                           Newlands        7
46                 JSCA International Stadium Complex        7
47                                   Barabati Stadium        7
48   Shaheed Veer Narayan Singh International Stadium        6
49  Himachal Pradesh Cricket Association Stadium, ...        6
50  Punjab Cricket Association IS Bindra Stadium, ...        5
51                                      Nehru Stadium        5
52  Maharaja Yadavindra Singh International Cricke...        5
53                                         Green Park        4
54  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        4
55       Vidarbha Cricket Association Stadium, Jamtha        3
56                              De Beers Diamond Oval        3
57                                       Buffalo Park        3
58                                    OUTsurance Oval        2

In [47]:
q(""" SELECT venue, COUNT(*) AS matches
FROM matches
GROUP BY venue
ORDER BY matches DESC LIMIT 5;""")

                      venue  matches
0              Eden Gardens       77
1          Wankhede Stadium       73
2     M Chinnaswamy Stadium       65
3          Feroz Shah Kotla       60
4  Wankhede Stadium, Mumbai       57

In [48]:
q(""" SELECT batter, COUNT(*) AS deliveries_faced
FROM deliveries
GROUP BY batter;""")

             batter  deliveries_faced
0    A Ashish Reddy               196
1          A Badoni               865
2        A Chandila                 7
3          A Chopra                75
4       A Choudhary                20
..              ...               ...
722   Yashpal Singh                67
723     Younis Khan                 7
724   Yudhvir Singh                16
725    Yuvraj Singh              2207
726          Z Khan               141

[727 rows x 2 columns]

In [49]:
q(""" SELECT batter, COUNT(*) AS deliveries_faced
FROM deliveries
GROUP BY batter HAVING deliveries_faced > 1000;""")

            batter  deliveries_faced
0   AB de Villiers              3487
1     AC Gilchrist              1555
2       AD Russell              1626
3         AJ Finch              1696
4       AK Markram              1231
..             ...               ...
84         VR Iyer              1139
85         WP Saha              2368
86     YBK Jaiswal              1663
87       YK Pathan              2334
88    Yuvraj Singh              2207

[89 rows x 2 columns]

In [50]:
q(""" SELECT season, COUNT(*) AS matches
FROM matches
GROUP BY season HAVING matches > 50;""")

     season  matches
0      2008       58
1      2009       57
2      2010       60
3      2011       73
4      2012       74
5      2013       76
6      2014       60
7      2015       59
8      2016       60
9      2017       59
10     2018       60
11     2019       60
12  2020/21       60
13     2021       60
14     2022       74
15     2023       74
16     2024       71
17     2025       74

In [51]:
q(""" SELECT venue, COUNT(*) AS matches
FROM matches
GROUP BY venue HAVING matches > 20;""")

                                                venue  matches
0                         Arun Jaitley Stadium, Delhi       27
1   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26
2                 Dubai International Cricket Stadium       46
3                                        Eden Gardens       77
4                               Eden Gardens, Kolkata       27
5                                    Feroz Shah Kotla       60
6                               M Chinnaswamy Stadium       65
7                    M Chinnaswamy Stadium, Bengaluru       24
8                     MA Chidambaram Stadium, Chepauk       48
9            MA Chidambaram Stadium, Chepauk, Chennai       38
10            Maharashtra Cricket Association Stadium       22
11                   Narendra Modi Stadium, Ahmedabad       37
12         Punjab Cricket Association Stadium, Mohali       35
13          Rajiv Gandhi International Stadium, Uppal       49
14  Rajiv Gandhi International Stadium, Uppal, Hyd...       23
15                             Sawai Mansingh Stadium       47
16                            Sharjah Cricket Stadium       28
17                               Sheikh Zayed Stadium       29
18                                   Wankhede Stadium       73
19                           Wankhede Stadium, Mumbai       57

In [52]:
q(""" SELECT batter, COUNT(DISTINCT match_id) AS matches_played
FROM deliveries
GROUP BY batter
HAVING matches_played > 100;""")

            batter  matches_played
0   AB de Villiers             170
1       AD Russell             114
2        AM Rahane             191
3         AR Patel             129
4        AT Rayudu             185
5      BB McCullum             109
6         CH Gayle             141
7        DA Miller             140
8        DA Warner             184
9         DJ Bravo             110
10        DJ Hooda             101
11    F du Plessis             147
12       G Gambhir             151
13      GJ Maxwell             134
14       HH Pandya             147
15    Ishan Kishan             121
16      JC Buttler             128
17      KA Pollard             168
18      KD Karthik             233
19       KH Pandya             118
20        KL Rahul             144
21         M Vijay             105
22      MA Agarwal             125
23       MK Pandey             161
24      MP Stoinis             104
25        MS Dhoni             241
26          N Rana             119
27        PA Patel             136
28       Q de Kock             118
29       RA Jadeja             201
30       RG Sharma             270
31         RR Pant             131
32      RV Uthappa             197
33        S Dhawan             221
34        SA Yadav             159
35        SK Raina             200
36       SP Narine             122
37       SR Watson             141
38         SS Iyer             138
39       SV Samson             179
40    Shubman Gill             122
41         V Kohli             268
42        V Sehwag             104
43         WP Saha             143
44       YK Pathan             153
45    Yuvraj Singh             126

In [53]:
q(""" SELECT d.match_id,p.player_name,p.player_full_name
FROM deliveries d
JOIN players p
ON d.batter = p.player_name;""")

        match_id player_name          player_full_name
0        1082635  MN Samuels  Marlon Nathaniel Samuels
1        1082635  MN Samuels  Marlon Nathaniel Samuels
2        1082635  MN Samuels  Marlon Nathaniel Samuels
3        1082635  MN Samuels  Marlon Nathaniel Samuels
4        1082635  MN Samuels  Marlon Nathaniel Samuels
...          ...         ...                       ...
288221   1529286      N Rana               Nitish Rana
288222   1529286      N Rana               Nitish Rana
288223   1529286      N Rana               Nitish Rana
288224   1529282   SU Parakh        Sahil Ulhas Parakh
288225   1529282   SU Parakh        Sahil Ulhas Parakh

[288226 rows x 3 columns]

In [54]:
q(""" SELECT venue
FROM venues
EXCEPT
SELECT DISTINCT venue
FROM matches;""")

Empty DataFrame
Columns: [venue]
Index: []

In [55]:
q(""" SELECT match_id,innings,over_number,ball_number,count(*) as N
FROM deliveries
GROUP BY match_id,innings,over_number,ball_number;""")

        match_id  innings  over_number  ball_number  N
0         335982        1            0            0  1
1         335982        1            0            1  1
2         335982        1            0            2  1
3         335982        1            0            3  1
4         335982        1            0            4  1
...          ...      ...          ...          ... ..
288221   1529286        2           18            3  1
288222   1529286        2           18            4  1
288223   1529286        2           18            5  1
288224   1529286        2           19            0  1
288225   1529286        2           19            1  1

[288226 rows x 5 columns]

In [56]:
q(""" SELECT COUNT(DISTINCT batter)
FROM deliveries
WHERE batter NOT IN (SELECT player_name FROM players);""")

   COUNT(DISTINCT batter)
0                       0

In [57]:
q(""" SELECT COUNT(*) AS TOTAL,
SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END) AS NULL_CITY
FROM matches;""")

   TOTAL  NULL_CITY
0   1212         51

In [58]:
q(""" SELECT COUNT(*) AS TOTAL,
SUM(CASE WHEN venue IS NULL THEN 1 ELSE 0 END) AS NULL_CITY
FROM matches;""")

   TOTAL  NULL_CITY
0   1212          0

In [60]:
q(""" SELECT venue,COUNT(*) AS matches_hosted
FROM matches
GROUP BY venue
ORDER BY venue;""")

                                                venue  matches_hosted
0                                Arun Jaitley Stadium              14
1                         Arun Jaitley Stadium, Delhi              27
2                                    Barabati Stadium               7
3                 Barsapara Cricket Stadium, Guwahati               8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...              26
5                                   Brabourne Stadium              10
6                           Brabourne Stadium, Mumbai              17
7                                        Buffalo Park               3
8                               De Beers Diamond Oval               3
9                          Dr DY Patil Sports Academy              17
10                 Dr DY Patil Sports Academy, Mumbai              20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...              13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...               4
13                Dubai International Cricket Stadium              46
14                                       Eden Gardens              77
15                              Eden Gardens, Kolkata              27
16                                   Feroz Shah Kotla              60
17                                         Green Park               4
18       Himachal Pradesh Cricket Association Stadium               9
19  Himachal Pradesh Cricket Association Stadium, ...               6
20                             Holkar Cricket Stadium               9
21                 JSCA International Stadium Complex               7
22                                          Kingsmead              15
23                              M Chinnaswamy Stadium              65
24                   M Chinnaswamy Stadium, Bengaluru              24
25                              M.Chinnaswamy Stadium              15
26                             MA Chidambaram Stadium               9
27                    MA Chidambaram Stadium, Chepauk              48
28           MA Chidambaram Stadium, Chepauk, Chennai              38
29  Maharaja Yadavindra Singh International Cricke...              10
30  Maharaja Yadavindra Singh International Cricke...               5
31            Maharashtra Cricket Association Stadium              22
32      Maharashtra Cricket Association Stadium, Pune              13
33                   Narendra Modi Stadium, Ahmedabad              37
34                                      Nehru Stadium               5
35                              New Wanderers Stadium               8
36                                           Newlands               7
37                                    OUTsurance Oval               2
38       Punjab Cricket Association IS Bindra Stadium              10
39  Punjab Cricket Association IS Bindra Stadium, ...              11
40  Punjab Cricket Association IS Bindra Stadium, ...               5
41         Punjab Cricket Association Stadium, Mohali              35
42                 Rajiv Gandhi International Stadium              15
43          Rajiv Gandhi International Stadium, Uppal              49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...              23
45                       Sardar Patel Stadium, Motera              12
46             Saurashtra Cricket Association Stadium              10
47                             Sawai Mansingh Stadium              47
48                     Sawai Mansingh Stadium, Jaipur              19
49   Shaheed Veer Narayan Singh International Stadium               6
50                            Sharjah Cricket Stadium              28
51                               Sheikh Zayed Stadium              29
52                                   St George's Park               7
53                         Subrata Roy Sahara Stadium              16
54                                    SuperSport Park              12
55       Vidarbha Cricket Association Stadium, Jamtha               3
56                                   Wankhede Stadium              73
57                           Wankhede Stadium, Mumbai              57
58                   Zayed Cricket Stadium, Abu Dhabi               8

In [ ]:
# issue:remove str after ,
# count of distinct venues after removing the part after the comma
q("""
SELECT COUNT(DISTINCT
    CASE
        WHEN INSTR(venue, ',') > 0
            THEN TRIM(SUBSTR(venue, 1, INSTR(venue, ',') - 1))
        ELSE TRIM(venue)
    END
) AS after_coma
FROM matches;
""")

   after_coma
0          42

In [72]:
q(""" SELECT COUNT(*) AS rows, 
COUNT(DISTINCT venue) AS distinct_hosted
FROM venues;""")

   rows  distinct_hosted
0    63               59

In [ ]:
# ISSUE:same venues have different id
q(""" SELECT venue,COUNT(*) AS n
FROM venues
GROUP BY venue
HAVING COUNT(*)>1;""")

                                               venue  n
0                 Dr DY Patil Sports Academy, Mumbai  2
1                Dubai International Cricket Stadium  2
2  Maharaja Yadavindra Singh International Cricke...  2
3                            Sharjah Cricket Stadium  2

In [76]:
q(""" SELECT team_name,
(SELECT COUNT(*) FROM matches m
WHERE m.team1=t.team_name OR m.team2=t.team_name) AS matches_played
FROM teams t
ORDER BY team_name;""")

                      team_name  matches_played
0           Chennai Super Kings             260
1               Deccan Chargers               0
2                Delhi Capitals             276
3                 Gujarat Lions              30
4                Gujarat Titans              69
5          Kochi Tuskers Kerala              14
6         Kolkata Knight Riders             272
7          Lucknow Super Giants              66
8                Mumbai Indians             285
9                 Pune Warriors              46
10                 Punjab Kings             272
11             Rajasthan Royals             245
12       Rising Pune Supergiant              30
13      Rising Pune Supergiants               0
14  Royal Challengers Bangalore             279
15          Sunrisers Hyderabad             280

In [77]:
q(""" SELECT result, COUNT(*) AS count
FROM matches
GROUP BY result;""")

      result  count
0  no result      9
1        tie     16
2        win   1187

In [78]:
# checking contradiction between match_winner and result
q(""" SELECT match_winner, result, season,match_id
FROM matches
WHERE result='no result' AND match_winner IS NOT NULL;""")

            match_winner     result season  match_id
0       Rajasthan Royals  no result   2019   1178424
1    Chennai Super Kings  no result   2023   1359519
2          Pune Warriors  no result   2011    501265
3       Rajasthan Royals  no result   2015    829763
4         Delhi Capitals  no result   2015    829813
5  Kolkata Knight Riders  no result   2025   1473481
6    Sunrisers Hyderabad  no result   2025   1473492
7         Delhi Capitals  no result   2025   1473495
8           Punjab Kings  no result   2026   1527685